apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6sdi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6sdi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6sdi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6sdi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6sdi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mris-tenant/rhtap-demo-app/hacbs-test-project-6sdi@sha256:f415b0d16407d9ada50ab889f43f0755a0cf5d68c7d9cb682571c904717853a5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
